# Compare model outputs 

# This script compares differences in model outputs generated by
# two different model runs and outputs the differences in a .csv file.

source("./src/comparison-tools/comparison-functions.R")

# ==============================================================================
# Read Files
# ==============================================================================

test_path <-  "./src/comparison-tools/test-cases/"

# Guidance
guide1 <- paste0(test_path, "test-compare-guidance-1.csv")
guide2 <- paste0(test_path, "test-compare-guidance-2.csv")

# Partial controllability matrices
pc1 <- paste0(test_path, "test-compare-partcontrol_matrices-1.csv")
pc2 <- paste0(test_path, "test-compare-partcontrol_matrices-2.csv")

# Policies
pol1 <- paste0(test_path, "test-compare-policies-1.csv")
pol2 <- paste0(test_path, "test-compare-policies-2.csv")

# Transition matrices
tm1 <- paste0(test_path, "test-compare-transition_matrices-1.csv")
tm2 <- paste0(test_path, "test-compare-transition_matrices-2.csv")

# ==============================================================================
#  Find Differences
# ==============================================================================

# Compare guidance outputs  
guidanceDiff(guide1, guide2, cycleend = 2100)

# Compare partial controllability outputs 
partControlDiff(pc1, pc2, cycleend = 2100)

# Compare policy differences  
policyDiff(pol1, pol2, cycleend = 2100)

# Compare policy differences  
transitionDiff(tm1, tm2, cycleend = 2100)

# ==============================================================================
#  Clean Up
# ==============================================================================
rm(test_path, guide1, guide2, pc1, pc2, pol1, pol2, tm1, tm2)
