# Functions for reading information from cumulative outputs associated with
# previous / older model runs. These functions are called only when the model
# run involves information from 2024 or earlier.
#
# Functions
#  * readPreviousOutputs  : Gets the desired output from the previous model runs
#                           (and ignores information prior to that)
#  * skipYearMessage      : Generates a warning message based on file name and
#                           year
#  * readTransitions2018  : Put transition probabilities in a standardized order
#                           and append the cycle_used column
#  * readPCmatrix2018     : Read the initial partial controllability matrix and
#                           format it in a way that the model will recognize
#  * readPreUpdateGuidance  : Get the released guidance from a previous year. If
#                           no such file exists, use the one generated by the
#                           designated previous run-- but with a warning.
#  * writePreUpdateGuidance : Build the guidance history from the official
#                           guidance of 2018-2024
##

readPreviousOutputs <- function(file_name, cycleend, run_path) {
  # Gets the desired output from the previous model runs (and ignores
  # information prior to that)
  #
  # INPUT
  # file_name : the first part of the file name to read (character)
  # cycleend  : the second/final year of the current cycle (numeric)
  # run_path  : path to the file (character)
  #
  # OUTPUT
  # the most recently added rows of the file (data frame)
  ##

  all_rows <- read.csv(paste0(run_path, file_name, "-NOT-UPDATED.csv"),
    stringsAsFactors = FALSE
  )
  if (file_name == "guidance") {
    rows <- all_rows[all_rows$recommend_cycle == (cycleend - 1), ]
    if (nrow(rows) == 0) { # No updates last year
      warning(skipYearMessage(file_name, cycleend))
      rows <- all_rows[all_rows$recommend_cycle == max(all_rows$recommend_cycle), ]
    }
  } else {
    rows <- all_rows[all_rows$cycle_used == (cycleend - 1), ]
    if (nrow(rows) == 0) { # No updates last year
      warning(skipYearMessage(file_name, cycleend))
      rows <- all_rows[all_rows$cycle_used == max(all_rows$cycle_used), ]
    }
  }

  return(rows)
}

skipYearMessage <- function(file_name, cycleend) {
  # Generates a warning message based on file name and year
  if (file_name == "transition_matrices") {
    return(paste0(
      "No transition updates for ", cycleend - 1, "-", cycleend,
      ". Using data from the most recent cycle"
    ))
  }
  if (file_name == "partcontrol_matrices") {
    return(paste0(
      "No partial controllability updates for ", cycleend - 1, "-",
      cycleend, ". Using data from the most recent cycle"
    ))
  }
  if (file_name == "guidance") {
    return(paste0(
      "No guidance released in ", cycleend - 1, "-", cycleend,
      ". Using data from the most recent cycle"
    ))
  }
} # end of skipYearMessage

readTransitions2018 <- function() {
  # Put transition probabilities in a standardized order and append the
  # cycle_used column
  #
  # INPUT
  # none
  #
  # OUTPUT
  # transitions : a data frame whose rows represent all possible state-to-state
  #               transitions under each management combination
  #
  # ASSUMPTIONS
  #  * File paths to helper functions, initial input data have not changed
  #    since I wrote this function
  ##

  transitions <- read.csv("./src/run-model/initial-inputs/repaired_priors.csv",
    stringsAsFactors = FALSE
  )

  # Make sure that it's in standardized order (all transitions out of each state
  # grouped together; starting states grouped within management combinations
  transitions <- transitions[order(
    transitions$mnt_comb, transitions$state_begin,
    transitions$state_end
  ), ]

  cycle_used <- rep(CYCLEEND, nrow(transitions))
  transitions <- cbind(transitions, cycle_used)

  return(transitions)
} # end readTransitions2018

readPCmatrix2018 <- function() {
  # Read the initial partial controllability matrix and format it in a way that
  # the model will recognize
  #
  # INPUT
  # none
  #
  # OUTPUT
  # partial controllability matrix, matrix format
  #
  # ASSUMPTIONS
  #  * File paths to helper functions, initial input data have not changed
  #    since I wrote this function
  ##
  pc_matrix <- read.csv("./src/run-model/initial-inputs/pc-initial-matrix.csv",
    stringsAsFactors = FALSE
  )

  # The '+' character doesn't read in correctly and the row names appear in the
  # first column. Rename the columns, name the rows, and drop the first column
  mnt_combs <- pc_matrix[, 1]
  pc_matrix <- pc_matrix[, 2:ncol(pc_matrix)]
  colnames(pc_matrix) <- mnt_combs
  rownames(pc_matrix) <- mnt_combs

  ## Since there was no guidance prior to 2018, there's nothing to update the
  #  matrix with. But since pc_matrix is the basis of next year's update, read
  #  the initial matrix in table format and write it to file.
  ##
  pc_table <- read.csv("./src/run-model/initial-inputs/pc-initial-table.csv",
    stringsAsFactors = FALSE
  )

  # add a column indicating the year that the matrix was applied to the
  # optimization and save for later
  cycle_used <- rep(2018, nrow(pc_table))
  writeOutput(cbind(pc_table, cycle_used), "partcontrol_matrices", RUNPATH)

  return(as.matrix(pc_matrix)) # it was read in as a dataframe; convert to matrix
} # end readPCmatrix2018

readPreUpdateGuidance <- function(file_name, cycleend, run_path) {
  # Get the released guidance from a previous year. If no such file exists, use
  # the one generated by the designated previous run-- but with a warning.
  #
  # INPUT
  # file_name : the entire file name to read (character)
  # cycleend  : the second/final year of the current cycle (numeric)
  # run_path  : path to the file (character)
  #
  # OUTPUT
  # a data frame
  #
  # ASSUMPTIONS
  #   * guidance generated by the 2018 and 2019 model runs has been copied into
  #     the appropriate directory
  ##

  if (length(grep(file_name, list.files(run_path))) == 0) {
    # The released guidance is not in run_path

    warning(paste0(
      "readPreUpdateGuidance: Guidance released in ", (cycleend - 1),
      " is not in ", run_path,
      ". Using the guidance from the your selected previous run.",
      "Updated guidance may not reflect PAMF history."
    ))

    old_guidance <- read.csv(paste0(run_path, "guidance-NOT-UPDATED.csv"),
      stringsAsFactors = FALSE
    )
    return(old_guidance[old_guidance$recommend_cycle == (cycleend - 1), ])
  } else {
    # The file exists in the model run directory
    return(read.csv(paste0(run_path, file_name), stringsAsFactors = FALSE))
  }
} # end readPreUpdateGuidance

writePreUpdateGuidance <- function(guidance, cycleend, run_path) {
  
  # Build the guidance history from the official guidance of previous model runs
  #
  # INPUT
  # guidance  : guidance generated by the current model run (data frame)
  # cycleend  : the second/final year of the current cycle (numeric)
  # run_path  : path to the current model run (character)
  #
  # OUTPUT
  # none
  #
  # ASSUMPTIONS
  #   * readPreUpdateGuidance() is sourced
  #   * official guidance generated by the previous model runs has
  #     been copied into the appropriate directory
  ##
  
  # Columns to keep in the guidance files
  keep_cols <- c(
    "munitid", "state", "transrec", "dormrec",
    "growrec", "optimal", "recommend_cycle",
    "recommenddate"
  )
  
  years <- 2018:(cycleend - 1)
  
  # Read all previous guidance files
  prev <- lapply(years, function(y) {
    df <- readPreUpdateGuidance(
      GUIDANCE_FILES[as.character(y)],
      cycleend,
      run_path
    )
    
    if (y %in% c(2018, 2019)) {
      df$recommend_cycle <- y
      
      # Remove obsolete columns from old guidance files
      df <- df[, keep_cols]
    }
    
    df
  })
  
  # Combine all the previous guidance
  prev_guidance <- do.call(rbind, prev)
  
  # Align columns with columns of newly generated guidance
  prev_guidance <- prev_guidance[, keep_cols]
  
  # Convert date to character before writing
  guidance$recommenddate <- as.character(guidance$recommenddate)
  
  # Concatenate and write
  write.csv(
    rbind(prev_guidance, guidance),
    paste0(run_path, "guidance.csv"),
    row.names = FALSE
  )
  
  # Remove the 'NOT-UPDATED' version of previous run's guidance
  unlink(paste0(run_path, "guidance-NOT-UPDATED.csv"))
} # end writePreUpdateGuidance
