# Some functions to get near-optimal (but still good) management
# recommendation policies
#
# Functions:
# eval_policy_optimality_proportion : Find near-optimal policies within a given
#                                     percentage of optimal policy
# convertNOP         : Convert near-optimal policy output to dataframe,
#                      including an epsilon column
# nop2action         : Map near-optimal results to PAMF combinations
#                      analogous to policy2action()

# UNUSED FUNCTIONS
# Note that these functions are not currently used in the PAMF Model but are
# kept here for posterity or in case we want to change the code later to
# incorporate these

# eval_policy_optimality : Find near-optimal policies within a given epsilon of
#                          optimal policy
# convertNOP_epsilon : Convert near-optimal policy output to dataframe,
#                      including an epsilon column
# n_near_optimal     : Find at least n near-optimal actions for each state
##

eval_policy_optimality_proportion <- function(P, R, discount, policy, proportion = 0.01) { # Modification of mdp_eval_policy_optimality with state-specific epsilon
  # values pinned to a user-defined proportion of the optimal expected values
  #
  # Since the optimal value varies by state, calculate an epsilon vector, and
  # compare each row against the epsilon value corresponding to that row's state
  # I've left the style mostly untouched.
  
  # Updated in July 2026 to also output the V and Q values:
  # V(s) is the state value: the expected total discounted reward obtained by
  # starting in state s and then following the policy thereafter.
  # V(s) = the value of the best policy at state s.
  # Q(s,a) is the action value: the expected total discounted reward obtained by
  # taking action a in state s, and then following the policy thereafter.
  # Q(s,a) = the value of a specific action at state s.
  
  # In this case, V comes from optimal policy value calculated by
  # mdp_eval_policy_matrix, and Q is the value generated by this function for
  # comparison.
  
  Vpolicy <- policy$V # so that I can mapply this across a list of policies
  
  if (discount <= 0 | discount > 1) {
    print("--------------------------------------------------------")
    print("ERROR: Discount rate must be greater than 0 and less than 1")
    print("--------------------------------------------------------")
  } else if (ifelse(is.list(P), length(Vpolicy) != dim(P[[1]])[1],
                    FALSE
  )) {
    print("--------------------------------------------------------")
    print("ERROR: policy must have the same dimension as P")
    print("--------------------------------------------------------")
  } else if (ifelse(!is.list(P), length(Vpolicy) != dim(P)[1],
                    FALSE
  )) {
    print("--------------------------------------------------------")
    print("MDP Toolbox ERROR: policy must have the same dimension as P")
    print("--------------------------------------------------------")
  } else {
    PR <- mdp_computePR(P, R)
    if (is.list(P)) {
      S <- dim(P[[1]])[1]
      A <- length(P)
      Q <- matrix(0, S, A)
      for (a in 1:A) {
        Q[, a] <- as.matrix(PR[, a] + discount * P[[a]] %*%
                              Vpolicy)
      }
    } else {
      S <- dim(P)[1]
      A <- dim(P)[3]
      Q <- matrix(0, S, A)
      for (a in 1:A) {
        Q[, a] <- PR[, a] + discount * P[, , a] %*% Vpolicy
      }
    }
    # pin epsilon to a proportion of Vpolicy
    epsilon <- proportion * Vpolicy
    
    # Make a matrix to hold the results
    optimal_actions <- matrix(
      NA,
      nrow = S,
      ncol = A
    )
    
    # Mark the near-optimals as 0
    optimal_actions[
      abs(Q - matrix(rep(Vpolicy, A), length(Vpolicy), A)) < epsilon
    ] <- 0
    
    # Mark the optimals as 1
    optimal_actions[
      abs(Q - matrix(rep(Vpolicy, A), length(Vpolicy), A)) < .Machine$double.eps^0.5
    ] <- 1
    
    # All values that are neither optimal nor near-optimal will have values of
    # NA
    
    # Return all the policy values and the optimal actions
    return(
      list(
        optimal_actions = optimal_actions,
        Q = Q,
        V = Vpolicy
      )
    )
  }
} # end eval_policy_optimality_proportion

convertNOP <- function(nop_matrix, Q = NULL, V = NULL) {
  # Converts the optimal_actions output of eval_policy_optimality_proportion()
  # into a data frame whose rows contain one state-action pair
  #
  # INPUT
  # nop_matrix : near-optimal policy matrix, whose rows are states, whose
  #              columns are actions, and whose values are:
  #               1   # optimal
  #               0   # near-optimal
  #               NA  # neither optimal nor near-optimal
  # Q : matrix of Q values (numeric) from eval_policy_optimality_proportion()
  # V : matrix of V values (numeric) from eval_policy_optimality_proportion()
  #
  # OUTPUT
  # A data frame whose rows contain one state-action pair, along with the
  # Q and V values used in the calculation of optimal_actions
  ##
  
  n_states <- nrow(nop_matrix)
  n_actions <- ncol(nop_matrix)
  
  nop_df <- data.frame(
    state   = rep(seq_len(n_states), times = n_actions),
    act_ind = rep(seq_len(n_actions), each = n_states),
    optimal = as.vector(nop_matrix)
  )
  
  if (!is.null(Q)) {
    nop_df$Q <- as.vector(Q)
  }
  
  if (!is.null(V)) {
    nop_df$V <- rep(V, times = n_actions)
  }
  
  return(nop_df)
} # end convertNOP

nop2action <- function(near_optimal, policy_id, restr_combs, mc_maps) {
  # Convert near-optimal policy outputs to sets of management combinations that
  # are recognizable to the database
  #
  # INPUTS
  # near_optimal   : Near-optimal actions by state (data frame)
  # policy_id      : The ID of the restriction type used to generate
  #                  policy, as listed in policy_definitions (integer)
  # restr_combs    : Vector of management combinations (model encoding) allowed
  #                  by the restrictions used when policy was created (character)
  # mc_maps        : Defines the mapping between the model and database
  #                  management action codes (data frame)
  #
  # OUTPUT
  # Database containing management combinations and per-phase actions for
  # all combinations of restriction and invasion state
  #
  # ASSUMPTIONS
  # * near_optimal has the following columns
  #   state
  #   act_ind
  # * mnt_combs contains management combinations as recognized by the
  #   model, e.g., "GPF", "GRR", etc
  # * Management combinations in mnt_combs are in the SAME order as they
  #   were when the MDP solver was run to generate policy
  # * mc_maps has the following columns:
  #     db_tloc
  #     db_dorm
  #     db_grow
  #     mnt_code
  ##
  
  # Get the mnt_codes corresponding to near_optimal$act_ind
  mnt_comb <- restr_combs[near_optimal$act_ind]
  
  # Now get the db_tr, db_do, and db_gr values corresponding with each mnt_code
  db_codes <- mc_maps[match(mnt_comb, mc_maps$mnt_comb), c(
    "db_tloc", "db_dorm",
    "db_grow"
  )]
  
  # create the restr_id column
  restr_id <- rep(policy_id, length(mnt_comb))
  
  # get the state column
  state <- near_optimal$state
  
  out <- data.frame(
    restr_id = restr_id,
    state = state,
    db_codes,
    mnt_comb = mnt_comb,
    stringsAsFactors = FALSE
  )
  
  if ("optimal" %in% names(near_optimal)) {
    out$optimal <- near_optimal$optimal
  }
  
  if ("V" %in% names(near_optimal)) {
    out$V <- near_optimal$V
  }
  
  if ("Q" %in% names(near_optimal)) {
    out$Q <- near_optimal$Q
  }
  
  out
} # end nop2action

# UNUSED FUNCTIONS -------------------------------------------------------------

eval_policy_optimality <- function(P, R, discount, Vpolicy, epsilon = 0.01) { # Modification of mdp_eval_policy_optimality (MDPToolbox) to allow
  # user-defined epsilon. The rest of the function is left untouched.
  # In the absence of epsilon input, defaults to 0.01 as in the
  # original function.
  
  if (discount <= 0 | discount > 1) {
    print("--------------------------------------------------------")
    print("ERROR: Discount rate must be in ]0; 1]")
    print("--------------------------------------------------------")
  } else if (ifelse(is.list(P), length(Vpolicy) != dim(P[[1]])[1],
                    FALSE
  )) {
    print("--------------------------------------------------------")
    print("ERROR: policy must have the same dimension as P")
    print("--------------------------------------------------------")
  } else if (ifelse(!is.list(P), length(Vpolicy) != dim(P)[1],
                    FALSE
  )) {
    print("--------------------------------------------------------")
    print("MDP Toolbox ERROR: policy must have the same dimension as P")
    print("--------------------------------------------------------")
  } else {
    PR <- mdp_computePR(P, R)
    if (is.list(P)) {
      S <- dim(P[[1]])[1]
      A <- length(P)
      Q <- matrix(0, S, A)
      for (a in 1:A) {
        Q[, a] <- as.matrix(PR[, a] + discount * P[[a]] %*%
                              Vpolicy)
      }
    } else {
      S <- dim(P)[1]
      A <- dim(P)[3]
      Q <- matrix(0, S, A)
      for (a in 1:A) {
        Q[, a] <- PR[, a] + discount * P[, , a] %*% Vpolicy
      }
    }
    optimal_actions <- abs(Q - matrix(
      rep(Vpolicy, A), length(Vpolicy),
      A
    )) < epsilon
    
    if (max(colSums(optimal_actions)) == 1) {
      is_multiple <- F
    } else {
      is_multiple <- T
    }
    return(list(multiple = is_multiple, optimal_actions = optimal_actions))
  }
} # end eval_policy_optimality

convertNOP_epsilon <- function(nop_matrix, epsilon) {
  # Converts the optimal_actions output of eval_policy_optimality() OR
  # mdp_eval_policy_optimality() into a data frame whose rows contain
  # one state-action pair, along with the epsilon value used in the calculation
  # of optimal_actions
  #
  # INPUT
  # nop_matrix : near-optimal policy matrix, whose rows are states, whose
  #              columns are actions, and whose values are logical (matrix)
  # epsilon    : threshold for near-optimality (double)
  #
  # OUTPUT
  # A data frame whose rows contain one state-action pair, along with the
  # epsilon value used in the calculation of optimal_actions
  ##
  
  # Create data frame to hold state & column index of near-optimal actions
  n_rows <- length(which(nop_matrix == TRUE)) # TRUE means near-optimal
  nop_df <- NULL
  
  # Populate the data frame
  n_states <- dim(nop_matrix)[1]
  for (s in 1:n_states) {
    act_ind <- which(nop_matrix[s, ] == TRUE) # vector of action indices
    state <- rep(s, length(act_ind)) # same-length vector of states
    eps <- rep(epsilon, length(act_ind))
    
    nop_df <- rbind(nop_df, cbind(eps, state, act_ind))
  }
  
  colnames(nop_df) <- c("epsilon", "state", "act_ind")
  return(data.frame(nop_df))
} # end convertNOP_epsilon

n_near_optimal <- function(P, R, V, d, n, epsilon = 0.01,
                           eps_increment = 0.001, result = NULL) {
  # For a given MDP and the values of its optimal policy, find at least
  # the first n near-optimal (within epsilon of optimal) actions for each
  # state (NOTE: this function is slow!)
  #
  # INPUT
  # P : Array of transition matrices where slice [,,a] holds transition
  #     probabilities between each set of states under action a
  # R : Array of reward matrices where slice [,,a] holds reward
  #     values for each state under action a
  # V : Values associated with each state under the optimal policy (vector)
  # d : the discount factor used to find the optimal policy (double)
  # n : number of near-optimal policies to find (integer)
  # epsilon       : Near-optimality threshold (double)
  # eps_increment : Amount by which to increase epsilon at every recursive
  #               : call (double)
  # result        : States and IDs of near-optimal actions (data frame)
  #
  # OUTPUT
  # A data frame with the following columns:
  #   epsilon
  #   state
  #   act_ind
  #
  # ASSUMPTIONS
  # * the following functions are already sourced:
  #    eval_policy_optimality()
  #    convertNOP_epsilon()
  # * pr_list contains the following elements:
  #   P : array of transition (probability) matrices
  #   R : array of reward matrices
  ##
  
  # Find actions that are within epsilon of optimal
  nop <- eval_policy_optimality(P, R, d, V, epsilon)$optimal_actions
  
  # convert to data frame
  nop_df <- convertNOP_epsilon(nop, epsilon)
  result <- rbind(result, nop_df)
  
  # Keep only rows that aren't duplicated in state and act_ind
  result <- result[which(!duplicated(result[, c("state", "act_ind")])), ]
  
  # Keep only the first (up to) n rows containing each state
  keep_rows <- NULL
  for (s in unique(result$state)) { # slow but this function is already slow.
    # will only ever loop 6 times per function call
    keep_rows <- rbind(
      keep_rows,
      na.omit(result[which(result$state == s)[1:n], ])
    )
  }
  result <- keep_rows
  
  # Check whether enough near-optimal policies have been found
  min_nop <- min(rowSums(nop))
  
  # Disallow n > number of possible actions
  if (n > dim(nop)[2]) {
    message("Requested number of near-optimal actions exceeds total actions. Returning all possible actions as near-optimal.")
  }
  n <- min(n, dim(nop)[2])
  
  if (min_nop < n) {
    # At least one state doesn't have enough near-optimal policies
    
    # increment the epsilon value. This can't be done with simple addition
    # because the R representation of the sum is often a little bit (~10^-17)
    # off from the mathematically correct value. Round to the correct value,
    # matching the the precision of eps_increment
    precision <- nchar(strsplit(as.character(eps_increment), "\\.")[[1]][2])
    epsilon <- round(epsilon + eps_increment, precision)
    
    result <- n_near_optimal(P, R, V, d, n, epsilon, eps_increment, result)
    return(result)
  } else { # enough near-optimal policies were found
    return(result)
  }
} # end n_near_optimal
