## 2020-11-16
#
#  Checks user input for issues (outlined below), and determines whether it's
#  possible to proceed to report-level data cleaning
#
# Sourced by: app.R
#
# DEPENDENCIES
# * Variables
#    input  : input from user interface (Create Model Run screen)
#    output : output to be displayed on user interface
#    oldmsg : the value of "messages" from the previous call to this function.
#             Needed for user override in case of errors==FALSE and warnings==TRUE
#             s.t. any warnings produced between button pushes are shown before
#             the user can move to the next page
# * Functions
#   From review-input-functions.R:
#    checkCSV
#    checkPrevRun
#    checkDBPull
#    extractDate
##

# ==============================================================================
#  Source functions
# ==============================================================================
# source("./src/review-input-functions.R") # This is already sourced in app.R

# ==============================================================================
# Define variables to keep track of whether there are issues &
# what the issues are
# ==============================================================================
proceed <- FALSE # don't proceed to next screen
errors <- FALSE # has the input produced errors?
warnings <- FALSE # has the input produced warnings?
messages <- NULL # tell the user about issues with inputs


# ==============================================================================
#  Conduct checks to make sure that inputs are valid:
# ==============================================================================
#  ISSUES THAT PRODUCE ERRORS
#  ~~~ the model cannot run if these issues are present ~~~
#  1.  cycleend < 2018 OR cycleend > current_year; cycleend not a number
#  2.  No prior model run selected (for cycles ending in 2019 or later)
#  3.  Cost constants file is wrong type
#  4.  Cost constants file does not contain cost information
#  5.  Enrollment file missing or wrong type
#  6.  Monitoring file missing or wrong type
#  7.  Management file missing or wrong type
#  8.  Management dates file missing or wrong type
#  9.  Necessary column(s) missing from enrollment data
#  10. Necessary column(s) missing from monitoring data
#  11. Necessary column(s) missing from management data
#  12. Necessary column(s) missing from application date data
#  13. Directory of prior model run is missing one or more cumulative output
#      files
#  14. One or more cumulative output files is missing necessary column(s)
#
#  ISSUES THAT PRODUCE WARNINGS
#  ~~~ model can be run but outputs may be wrong ~~~
#  15. Prior model run is not from the year before cycleend
#  16. Cost constants are from a past year
#  17. Cost constants are from a future year
#  18. database files are not all from the same database pull
#  19. cycleend is different from the year of the database pull
##

## 1.  cycleend < 2018 OR cycleend > current_year
#      Don't try to run model before 2018 or for the future
#
#      NOTE: I've set max and min values for the numericInput() widget that
#            collects cycleend, BUT those settings affect the widget's arrow
#            buttons but not keyboard input.
#            Since it's still possible to type out-of-range years AND TEXT(!!),
#            we still have to check for those
##
current_year <- as.numeric(format(Sys.time(), "%Y"))
cycleend <- input$cycleend # static copy of input for use throughout this script

if (is.na(cycleend)) {
  # User has entered a non-numeric value for cycleend
  errors <- TRUE
  messages <- paste(messages, "ERROR: Invalid cycle end value")
} else {
  # cycleend is numeric. But is it a year after the beginning of PAMF and from
  # a cycle that has already begun?
  if (cycleend < 2018) {
    errors <- TRUE
    messages <- paste(messages, "ERROR: Cycle end before 2018", sep = "\n")
  }
  if (cycleend > current_year) {
    errors <- TRUE
    messages <- paste(messages,
      "ERROR: Model can only be run for past or present years",
      sep = "\n"
    )
  }

  # ---- Remaining checks assume that cycleend is numeric ---------------------

  ## 2.  No prior model run selected (2019+)
  #      Need to know which prior model run to update
  #      The exception is 2018, the first model run: in that case, ignore the menu
  ##
  if (input$prevrun == "Select..." & cycleend != 2018) {
    errors <- TRUE
    messages <- paste(messages, "ERROR: No previous run selected", sep = "\n")
  }


  ##  3, 4. Cost constants file is wrong type
  #         These files are generated by hand, and displayed in the menu if their
  #         name contains the pattern ".csv". It's unlikely but not impossible
  #         that this pattern will show up in the name but not the file extension.
  #         Since I'm using a drop-down menu instead of a file upload box, I can't
  #         check the MIME type, but I can check the file extension and try to
  #         open the file if the selection ends in ".csv"
  #
  #         It's also possible that the internal structure of the file is incorrect
  #         If the type is .csv, open file and verify that it's cost data
  #
  ## 16, 17. Cost constants are from a year that does not belong to the current
  #          cycle. This is common because we don't update the cost information
  #          every year! but i want the user to know about it
  ##

  # Does the name of the selection end in .csv?
  selectend <- substr(
    input$costconst, nchar(input$costconst) - 3,
    nchar(input$costconst)
  )
  if (tolower(selectend) != ".csv") {
    errors <- TRUE
    messages <- paste(messages, "ERROR: Cost constants file not in .csv format",
      sep = "\n"
    )
  } else {
    # Open the file and check that it contains the column(s) we'd expect from the
    # cost constant file (although this file is created by hand, it's done in a
    # structured way and it should contain specific columns. ignore any extra
    # columns though)
    ##
    cost_path <- paste("./cost-constants", input$costconst, sep = "/")
    cost_consts <- tryCatch(read.csv(cost_path),
      error = function(e) {
        errors <- TRUE
        return("ERROR: cost constant file is empty")
      }
    )
    if (length(cost_consts) == 1) {
      errors <- TRUE
      messages <- paste(messages, cost_consts, sep = "\n")
    } else {
      if (sum(c("type", "name", "unit", "cost_per_unit", "herb_code", "cost_year")
      %in% colnames(cost_consts)) != 6) {
        errors <- TRUE
        messages <- paste(messages, "ERROR: Incorrect cost constant file", sep = "\n")
      } else { # check on the year
        if (length(unique(cost_consts$cost_year)) > 1) {
          warnings <- TRUE
          messages <- paste(messages, "WARNING: Cost constants are from multiple years",
            sep = "\n"
          )
        } else {
          if ((unique(cost_consts$cost_year) > cycleend)) {
            warnings <- TRUE
            messages <- paste(messages,
              "WARNING: Cost constants created after end of cycle to be analyzed",
              sep = "\n"
            )
          } else {
            if (unique(cost_consts$cost_year) < cycleend) {
              warnings <- TRUE
              messages <- paste(messages,
                "WARNING: Cost constants at least one year old",
                sep = "\n"
              )
            }
          }
        }
      }
    }
  }


  ##  5, 9.  Enrollment file missing or wrong type
  #          If neither is true, open file and verify that it's enrollment
  ##
  isok <- checkCSV("enroll", input$enroll$name, input$enroll$datapath, cycleend)
  if (isok$error == TRUE) {
    errors <- TRUE
  }
  if (!is.null(isok$message)) {
    messages <- paste(messages, isok$message, sep = "\n")
  }


  ##  6, 10.  Monitoring file missing or wrong type
  #           If neither is true, open file and verify that it's monitoring
  ##
  isok <- checkCSV("monitor", input$monitor$name, input$monitor$datapath, cycleend)
  if (isok$error == TRUE) {
    errors <- TRUE
  }
  if (!is.null(isok$message)) {
    messages <- paste(messages, isok$message, sep = "\n")
  }


  ##  7, 11.  Management file missing or wrong type
  #           If neither is true, open file and verify that it's management
  ##
  isok <- checkCSV("manage", input$manage$name, input$manage$datapath, cycleend)
  if (isok$error == TRUE) {
    errors <- TRUE
  }
  if (!is.null(isok$message)) {
    messages <- paste(messages, isok$message, sep = "\n")
  }


  ##  8, 12.  Management dates file missing or wrong type
  #           If neither is true, open file and verify that it's mangement dates
  ##
  isok <- checkCSV("mndates", input$mndates$name, input$mndates$datapath, cycleend)
  if (isok$error == TRUE) {
    errors <- TRUE
  }
  if (!is.null(isok$message)) {
    messages <- paste(messages, isok$message, sep = "\n")
  }


  ##  13. Directory of prior model run is missing one or more cumulative output
  #       files
  ##  14. One or more cumulative output files is missing necessary column(s)
  #       If so, the parts of the model that attempt to append information to
  #       these files will throw errors
  #
  #       2018 was the first model run; only check for runs after this
  ##
  if (cycleend > 2018 & input$prevrun != "Select...") {
    # Get the path to the previous run & define a list of files to check on
    prev_run <- input$prevrun
    prev_path <- paste("./model-runs/", prev_run, "/", sep = "")

    expected_files <- c(
      "cost_estimates.csv", "datpak.csv", "datpak_issues.csv",
      "guidance.csv", "manage_issues.csv", "monitor_issues.csv",
      "partcontrol_matrices.csv", "policies.csv",
      "transition_matrices.csv"
    )

    # Check for problems 13 & 14 in the previous run
    isok <- checkPrevRun(prev_path, expected_files)
    if (isok$error == TRUE) {
      errors <- TRUE
    }
    if (!is.null(isok$message)) {
      messages <- paste(messages, isok$message, sep = "\n")
    }
  }


  ##  15. Prior model run is not from the year before cycleend
  #       (ignore if cycleend is 2018: there are no runs prior to 2018)
  ##
  if (cycleend != 2018) {
    if (is.na(suppressWarnings(as.numeric(substr(input$prevrun, 1, 4))))) {
      # If the first four characters of input$prevrun aren't numeric AND
      # input$prevrun isn't the default "Select..." warn the user that the
      # selected prevrun violates naming conventions
      if (input$prevrun != "Select...") {
        warnings <- TRUE
        messages <- paste(messages,
          "WARNING: Previous run has nonstandard name \n Run names should begin with the year that the run was conducted",
          sep = "\n"
        )
      }
    } else {
      if (as.numeric(substr(input$prevrun, 1, 4)) > as.numeric(cycleend) - 1) {
        prevyear <- input$prevrun
        warnings <- TRUE
        messages <- paste(messages,
          paste0(
            "WARNING: Date stamp on previous run is not from ",
            (cycleend - 1)
          ),
          sep = "\n"
        )
      }
    }
  } else {
    # Let the user know that this input will be ignored.
    messages <- paste(messages, "NOTE: There are no model runs prior to 2018.",
      "Disregarding any input about previous run", "",
      sep = "\n"
    )
  }


  ##  18. data files are not all from the database pull
  #       If so, newer data packages from the more recent files may be missing
  #       pieces just because the older files don't cover the same years
  #
  #   NOTE: This section of code assumes that the name of each file from the
  #         database  pull contains the date that the pull was done (in YYYY-MM-DD
  #         format) and that it contains no other dates
  ##

  ## Get the file names. These will persist past the end of the script to be used
  #  to create the model run
  enrollname <- input$enroll$name
  monitorname <- input$monitor$name
  managename <- input$manage$name
  mndatename <- input$mndates$name
  file_names <- c(enrollname, monitorname, managename, mndatename)

  isok <- checkDBPull(file_names)
  if (isok$warning == TRUE) {
    warnings <- TRUE
  }
  if (!is.null(isok$message)) {
    messages <- paste(messages, isok$message, sep = "\n")
  }


  ##  19. cycleend is different from the year of the database pull
  # Get the year from each database pull, in numeric format
  ##
  pull_dates <- unlist(unique(lapply(file_names, extractDate)))
  pull_years <- as.numeric(substr(pull_dates, 1, 4))
  if (!is.element(cycleend, pull_years) & length(pull_years) > 0) {
    warnings <- TRUE
    messages <- paste(messages,
      "WARNING: The year ending the cycle that you want to analyze",
      "does not coincide with the pull date of any uploaded file",
      sep = "\n"
    )
  }

  ## Get the most recent date from pull_dates. This will be recorded as the
  #  end of the reporting period when the model run directory is created
  if (!is.null(pull_dates)) {
    pull_date <- max(as.Date(pull_dates))
  } else {
    pull_date <- NULL
  }
} # end of conditional on is.na(cycleend)

# ==============================================================================
#  END OF ERROR CHECKING ON USER INPUTS
#   Change proceed to TRUE if either of these cases is TRUE:
#   * errors and warnings are both FALSE
#     (i.e. no issues in inputs)
#   * errors is FALSE, warnings is TRUE, and messages == oldmsg
#     (i.e. the user has had a chance to view the warnings, and has decided to
#      proceed by hitting the button again)
#
#  If proceed==TRUE, create a new model run
# ==============================================================================

## If messages is no longer null, strip the leading '\n', which was added
#  during the first call to paste()
if (!is.null(messages)) {
  messages <- substr(messages, 2, nchar(messages))
}

# set proceed
if (errors == FALSE & warnings == FALSE) {
  # No issues with any of the inputs
  proceed <- TRUE
} else {
  if (errors == FALSE & warnings == TRUE) {
    # the only issues are warnings-- user may proceed with caution
    messages <- paste(messages, "",
      "*** To proceed without changes, click 'Review Reports' again ***",
      sep = "\n"
    )

    # If messages==oldmsg, no changes were made since the last warning-only
    # attempt, allow processing to move to next step
    if (messages == oldmsg) {
      proceed <- TRUE
    }
  }
}


# ==============================================================================
#  Clean up temporary variables
# ==============================================================================
suppressWarnings(rm(
  current_year, cycleend, selectend, cost_path, prev_run,
  prev_path, expected_files, isok, prevyear, pull_dates,
  pull_years
))
# Some of these variables are created inside of conditional and may not exist
# every time this script is run
